language: node_js
node_js:
 - "node"

cache: npm

script: npm run build

deploy:
 provider: pages
 skip_cleanup: true
 github_token: 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
 local_dir: dist
 on:
   branch: main