language: node_js
node_js:
 - "node"

cache: npm

script: npm run build

deploy:
 provider: pages
 skip_cleanup: true
 github_token: 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
 local_dir: dist
 on:
   branch: main